# Generated by Django 4.0.6 on 2022-07-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (هزار تومن)')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات (در صورت نیاز)')),
            ],
            options={
                'verbose_name': 'کیک',
                'verbose_name_plural': 'کیک ها',
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (هزار تومن)')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات (در صورت نیاز)')),
            ],
            options={
                'verbose_name': 'سالاد',
                'verbose_name_plural': 'سالاد ها',
            },
        ),
    ]
