# Generated by Django 4.0.6 on 2022-07-31 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم (به صورت جمع)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='اضافه شده در')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش در')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیحات (در صورت نیاز)')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (هزار تومن)')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='اضافه شده در')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش در')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('name',),
            },
        ),
    ]
