# Generated by Django 4.0.6 on 2022-07-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'کیک', 'verbose_name_plural': 'کیک ها'},
        ),
        migrations.AlterModelOptions(
            name='salad',
            options={'verbose_name': 'سالاد', 'verbose_name_plural': 'سالاد ها'},
        ),
    ]
